In [2]:
print("hello")

hello


In this progamming sesiotin I want to be familiar with the concept of tensors. Tesnsors are sum of arrays. 0D tensor is just a number like [8]. one D Tensor is an array including sume numbers such as [0,1,1,3]. Two D tensor is sum of two one D tensors like: [[0,1,1,3], [0,1,1,3]].
By tf.constant() we can make the tesors

In [3]:
import tensorflow as tf


In [4]:
tensor_zero_d= tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
tensor_one_d= tf.constant([0,2,-3])
print(tensor_one_d)

tf.Tensor([ 0  2 -3], shape=(3,), dtype=int32)


In [13]:
tensor_two_d= tf.constant([[0,2,-3],[5,4,-3],[6,2,90.2]])
print(tensor_two_d)

tf.Tensor(
[[ 0.   2.  -3. ]
 [ 5.   4.  -3. ]
 [ 6.   2.  90.2]], shape=(3, 3), dtype=float32)


In [15]:
tensor_three_d= tf.constant([[[0,2,-3],[5,4,-3]],[[0,2,-3],[5,4,-3]],[[0,2,-3],[5,4,-3]]])
print(tensor_three_d)

tf.Tensor(
[[[ 0  2 -3]
  [ 5  4 -3]]

 [[ 0  2 -3]
  [ 5  4 -3]]

 [[ 0  2 -3]
  [ 5  4 -3]]], shape=(3, 2, 3), dtype=int32)


In [18]:
tensor_four_d= tf.constant([[[[0,2,-3],[5,4,-3]],[[0,2,-3],[5,4,-3]],[[0,2,-3],[5,4,-3]],[[0,2,-3],[5,4,-3]],[[0,2,-3],[5,4,-3]],[[0,2,-3],[5,4,-3]]]])
print(tensor_four_d)

tf.Tensor(
[[[[ 0  2 -3]
   [ 5  4 -3]]

  [[ 0  2 -3]
   [ 5  4 -3]]

  [[ 0  2 -3]
   [ 5  4 -3]]

  [[ 0  2 -3]
   [ 5  4 -3]]

  [[ 0  2 -3]
   [ 5  4 -3]]

  [[ 0  2 -3]
   [ 5  4 -3]]]], shape=(1, 6, 2, 3), dtype=int32)


In [19]:
print(tensor_four_d.ndim)

4


In [31]:
m=tf.eye(
    num_rows=2,
    num_columns=2,
    batch_shape=[2],
    dtype=tf.dtypes.float64,
    name=2
)
print(m)

tf.Tensor(
[[[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]], shape=(2, 2, 2), dtype=float64)


In [39]:
k=tf.random.normal(
    shape=[3,1,1],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(k)

tf.Tensor(
[[[-0.10019948]]

 [[-0.02541872]]

 [[-0.64514923]]], shape=(3, 1, 1), dtype=float32)
