<a href="https://colab.research.google.com/github/Ali-mohammadi-design/Deep_learning/blob/main/Deep_Learning_1_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello")

hello


In this progamming sesiotin I want to be familiar with the concept of tensors. Tesnsors are sum of arrays. 0D tensor is just a number like [8]. one D Tensor is an array including sume numbers such as [0,1,1,3]. Two D tensor is sum of two one D tensors like: [[0,1,1,3], [0,1,1,3]].
By tf.constant() we can make the tesors

In [2]:
import tensorflow as tf


In [3]:
tensor_zero_d= tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d= tf.constant([0,2,-3])
print(tensor_one_d)

tf.Tensor([ 0  2 -3], shape=(3,), dtype=int32)


In [5]:
tensor_two_d= tf.constant([[0,2,-3],[5,4,-3],[6,2,90.2]])
print(tensor_two_d)

tf.Tensor(
[[ 0.   2.  -3. ]
 [ 5.   4.  -3. ]
 [ 6.   2.  90.2]], shape=(3, 3), dtype=float32)


In [6]:
tensor_three_d= tf.constant([[[0,2,-3],[5,4,-3]],[[0,2,-3],[5,4,-3]],[[0,2,-3],[5,4,-3]]])
print(tensor_three_d)

tf.Tensor(
[[[ 0  2 -3]
  [ 5  4 -3]]

 [[ 0  2 -3]
  [ 5  4 -3]]

 [[ 0  2 -3]
  [ 5  4 -3]]], shape=(3, 2, 3), dtype=int32)


In [7]:
tensor_four_d= tf.constant([[[[0,2,-3],[5,4,-3]],[[0,2,-3],[5,4,-3]],[[0,2,-3],[5,4,-3]],[[0,2,-3],[5,4,-3]],[[0,2,-3],[5,4,-3]],[[0,2,-3],[5,4,-3]]]])
print(tensor_four_d)

tf.Tensor(
[[[[ 0  2 -3]
   [ 5  4 -3]]

  [[ 0  2 -3]
   [ 5  4 -3]]

  [[ 0  2 -3]
   [ 5  4 -3]]

  [[ 0  2 -3]
   [ 5  4 -3]]

  [[ 0  2 -3]
   [ 5  4 -3]]

  [[ 0  2 -3]
   [ 5  4 -3]]]], shape=(1, 6, 2, 3), dtype=int32)


In [8]:
print(tensor_four_d.ndim)

4


In [9]:
m=tf.eye(
    num_rows=2,
    num_columns=2,
    batch_shape=[2],
    dtype=tf.dtypes.float64,
    name=2
)
print(m)

tf.Tensor(
[[[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]], shape=(2, 2, 2), dtype=float64)


In [10]:
k=tf.random.normal(
    shape=[3,1,1],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(k)

tf.Tensor(
[[[-0.12572639]]

 [[-0.19428489]]

 [[-0.0879982 ]]], shape=(3, 1, 1), dtype=float32)


In [24]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
a  # 2-D tensor
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
b  # 2-D tensor
c= tf.constant([7, 8, 9, 10], shape=[2, 2])
c  # 2-D tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10]], dtype=int32)>

In [31]:
d = tf.matmul(a,b)
e = tf.matmul(d,c)
e

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 982, 1104],
       [2359, 2652]], dtype=int32)>